### ISSUE TITLE
fix header nav bar

### ISSUE THREAD

**Issue by Gaddonisio** [chris-pardy/chris-pardy.github.io#18]
Ideas
- scroll up after intro like http://www.judieandz.com/ 
- static header above  like http://vinceandmarlene.com/ 
- static header with background change. and right intro http://mattandmallory.com/
- shows up after a certain pt http://portfoliolab.co.uk/wedding/

Add hover state to options
Options should scroll to section

**Comment by chris-pardy** [comment]
Option:
Similar to julieandz.com we could attach navigation to the bottom (or top) of the content on the landing page. and "detach" it as the content scrolls past.

**Comment by chris-pardy** [comment]
Animate indicator for position see http://yougottalovefrontend.com/
